=== HelioGuilherme66/gretl/doc/commands/genr_funcs.dtd
<!--
  DTD for gretl genr functions. Allin Cottrell 2008
 -->

<!ENTITY ndash  "&#8211;">
<!ENTITY lgr    "&#0955;">
<!ENTITY mu     "&#0956;">
<!ENTITY sigma  "&#0963;">
<!ENTITY rgr    "&#0961;">
<!ENTITY hellip "&#8230;">
<!ENTITY mdash  "&#8212;">
<!ENTITY latex  "LaTeX">
<!ENTITY minus  "&#8211;">
<!ENTITY par    "">
<!ENTITY eg     "e.g.">
<!ENTITY ie     "i.e.">

<!ELEMENT funcref (funclist)+>
<!ATTLIST funcref
   language    CDATA #REQUIRED
>

<!ELEMENT funclist (function)+>
<!ATTLIST funclist
   name    CDATA #REQUIRED
   ref     CDATA #REQUIRED
>

<!-- The description is the only element that is absolutely
     required of a function -->

<!ELEMENT function (fnargs?, description+)>

<!ATTLIST function
   name    CDATA #REQUIRED
   targ    CDATA #IMPLIED
   output  (scalar | series | matrix | smatrix |
            rvec | cvec | list | asinput) "series"
   altout  (none | scalar | series | matrix | list) "none"
>

<!ELEMENT fnargs       (fnarg)+>
<!ELEMENT examples     (example)+>
<!ELEMENT description  (para | code | pre | ilist | nlist | table)*>
<!ELEMENT gui-access   (menu-path, other-access?)>

<!ELEMENT fnarg (#PCDATA)>
<!ATTLIST fnarg 
    type      (scalar | series | vector | matrix | smatrix | symmat | 
               matrixref | anyfloat | scalar-or-series | series-or-vec | 
               list | coeffname | string | char | seebelow) "series"
    optional  (true | false) "false"
    alternate (true | false) "false"
>

<!ELEMENT example  (#PCDATA)>

<!ELEMENT menu-path    (#PCDATA)>
<!ELEMENT other-access (#PCDATA)>

<!ELEMENT para (#PCDATA | repl | program | mathvar | equation |
                lit | emphasis | book | quote | filename |
                func | guideref | cmdref | fncref | tabref | 
                footnote | argname | cmd)*>

<!ELEMENT pre (#PCDATA | repl | lit)*>
<!ELEMENT code (#PCDATA)>

<!ELEMENT ilist (li)+>
<!ELEMENT nlist (li)+>

<!ELEMENT li (para | code | table)*>

<!ELEMENT equation EMPTY>
<!ATTLIST equation
   status (inline | display) "inline"
   tex     CDATA #REQUIRED
   ascii   CDATA #REQUIRED
   graphic CDATA #IMPLIED
>

<!ELEMENT guideref EMPTY>
<!ATTLIST guideref
   targ    CDATA #REQUIRED
>

<!ELEMENT cmdref EMPTY>
<!ATTLIST cmdref
   targ    CDATA #REQUIRED
>

<!ELEMENT fncref EMPTY>
<!ATTLIST fncref
   targ    CDATA #REQUIRED
   label   CDATA #IMPLIED
>

<!ELEMENT tabref EMPTY>
<!ATTLIST tabref
   targ    CDATA #REQUIRED
>

<!ELEMENT footnote (para)+>

<!ELEMENT table (row)+>
<!ELEMENT row (cell)+>
<!ELEMENT cell (#PCDATA | lit | repl | emphasis | 
                func | mathvar | equation | book | quote)*>
<!ATTLIST table
   lwidth   CDATA #IMPLIED
   rwidth   CDATA #IMPLIED
   id       CDATA #IMPLIED
   title    CDATA #IMPLIED
   lhead    CDATA #IMPLIED
   rhead    CDATA #IMPLIED
   style (plain | lpara | rpara | allpara) "plain"
   context  (cli | gui | both) "both"
>

<!ELEMENT repl     (#PCDATA)>
<!ELEMENT argname  (#PCDATA)>
<!ELEMENT program  (#PCDATA)>
<!ELEMENT lit      (#PCDATA)>
<!ELEMENT emphasis (#PCDATA)>
<!ELEMENT book     (#PCDATA)>
<!ELEMENT quote    (#PCDATA | lit)*>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT func     (#PCDATA)>
<!ELEMENT cmd      (#PCDATA)>
<!ELEMENT mathvar  (#PCDATA | sub | super)*>
<!ELEMENT sub      (#PCDATA)>
<!ELEMENT super    (#PCDATA)>

<!ATTLIST repl
   quote (true | false) "false"
>

=== HelioGuilherme66/gretl/doc/commands/genr_funcs_pt.xml
<?xml version="1.0" encoding="ISO-8859-15" ?>
<!DOCTYPE funcref SYSTEM "genr_funcs.dtd">

<funcref language="portuguese">

  <funclist name="Acessores" ref="accessors">

    <function name="$ahat" section="access" output="series">
      <description>
	<para>
	  Tem que ser acedido após a estimação de um modelo de dados de
	  painel com efeitos fixos.
	  Retorna uma série contendo as estimativas dos efeitos fixos 
          individuais (interceptores unitários).
	</para>
      </description>
    </function>

    <function name="$aic" section="access" output="scalar">
      <description>
	<para>
	  Retorna o Critério de Informação de Akaike para o último modelo
	  estimado, se disponível. Consultar <guideref targ="select-criteria"/> para
	  detalhes sobre o cálculo.
	</para>
      </description>
    </function>

    <function name="$bic" section="access" output="scalar">
      <description>
	<para>
	  Retorna o Critério de Informação Bayesiano de Schwarz para o último modelo
	  estimado, se disponível. Consultar <guideref targ="select-criteria"/>
	  para  detalhes sobre o cálculo.
	</para>
      </description>
    </function>

    <function name="$chisq" section="access" output="scalar">
      <description>
	<para>
	  Retorna a estatística qui-quadrado global para o último modelo
	  estimado, se disponível.
	</para>
      </description>
    </function>

    <function name="$coeff" section="access" output="matrix" altort="scalar">
      <fnargs>
	<fnarg optional="true" type="coeffname">s</fnarg>
      </fnargs>
      <description>
	<para>
	  Sem argumentos, <lit>$coeff</lit> retorna um vector coluna
	  contendo os coeficientes estimados para o último modelo. Com o
	  argumento opcional do tipo texto retorna um escalar, designadamente o
	  parâmetro estimado com o nome <argname>s</argname>.
	  <seelist>
	    <fncref targ="$stderr"/>
	    <fncref targ="$vcv"/>
	  </seelist>
	</para>
	<para>
	  Exemplo:
	</para>
	<code>
	  open bjg
	  arima 0 1 1 ; 0 1 1 ; lg 
	  b = $coeff               # obtém um vector
	  macoef = $coeff(theta_1) # obtém um escalar
	</code>
	<para>
	  Se o <quote>modelo</quote> em questão é realmente um sistema,
	  o resultado depende das características do sistema: no caso de
	  VARs e VECMs o valor retornado é uma matriz com uma coluna
	  por equação, senão é um vector coluna contendo os coeficientes
          para a primeira equação seguidos pelos da segunda equação, e 
	  por aí adiante.
	</para>
      </description>
    </function>

    <function name="$command" section="access" output="string">
      <description>
	<para>
	  Tem que ser acedido após a estimação de modelo; retorna o nome
	  do comando, por exemplo <lit>ols</lit> ou <lit>probit</lit>.
	</para>
      </description>
    </function>

    <function name="$compan" section="access" output="matrix">
      <description>
	<para>
	  Tem que ser acedido após a estimação de VAR ou VECM; retorna a
	  matriz companheira.
	</para>
      </description>
    </function>

    <function name="$datatype" section="access" output="scalar">
      <description>
	<para>
	  Retorna um valor inteiro representando o tipo de conjunto de dados
	  que está carregado: 0 = sem dados; 1 = dados de secção-cruzada
	  (sem data); 2 = dados de série temporal; 3 = dados de painel.
	</para>
      </description>
    </function>

    <function name="$depvar" section="access" output="string">
      <description>
	<para>
	  Tem que ser acedido após a estimação de um modelo de equação singular;
	  retorna o nome da variável dependente.
	</para>
      </description>
    </function>

    <function name="$df" section="access" output="scalar">
      <description>
	<para>
	  Retorna os graus de liberdade do último modelo estimado. Se o
	  último modelo era na realidade um sistema de equações, o valor
	  retornado é o grau de liberdade por equação; se este for 
	  diferente nas equações então o valor é o número de observações
	  menos o número médio de coeficientes por equação (arredondado 
	  para o inteiro mais próximo). 
	</para>
      </description>
    </function>

    <function name="$dwpval" section="access" output="scalar">
      <description>
	<para>
	  Retorna o valor p para a estatística Durbin&ndash;Watson para
	  o último modelo estimado, se disponível.  Isto é determinado
	  usando um procedimento Imhof.
	</para>
      </description>
    </function>

    <function name="$ec" section="access" output="matrix">
      <description>
	<para>
	  Tem que ser acedido após a estimação de VECM; retorna a matriz
          contendo os termos de correção de erro.  O número de linhas é
          igual ao número de observações usadas e o número de colunas é
	  igual ao nível de cointegração do sistema.
	</para>
      </description>
    </function>

    <function name="$error" section="access" output="scalar">
      <description>
	<para>
	  Retorna o código de erro interno do programa, que será 
	  diferente de zero no caso de ter acontecido um erro mas 
	  este tenha sido apanhado num bloco <cmdref targ="catch"/>. 
	  Note que ao usar este acessor o código de erro interno 
          ficará reiniciado a zero. Consultar também <fncref targ="errmsg"/>.
	  Se você pretender uma mensagem de erro associada a um 
	  certo <lit>$error</lit> então tem que guardar o valor
	  numa variável temporária, tal como em
	</para>
	<code>
	  errval = $error
	  if (errval) 
	    printf "Obtido o erro %d (%s)\n", errval, errmsg(errval);
	  endif
	</code>
      </description>
    </function>

    <function name="$ess" section="access" output="scalar">
      <description>
	<para>
	  Retorna o erro de soma de quadrados do último modelo estimado,
	  se disponível.
	</para>
      </description>
    </function>

    <function name="$evals" section="access" output="matrix">
      <description>
	<para>
	  Tem que ser acedido após a estimação de VECM; retorna um vector
	  contendo os valores próprios que são utilizados no cálculo do
	  teste traço da cointegração.
	</para>
      </description>
    </function>

    <function name="$fcast" section="access" output="matrix">
      <description>
	<para>
	  Tem que ser acedido a seguir a um comando de predição 
	  <cmdref targ="fcast"/>; retorna os valores de predição
	  numa matriz. Se o modelo em que a predição se baseou é
	  um sistema de equações a matriz retornada terá uma coluna
	  por equação, caso contrário será um vector coluna. 
	</para>
      </description>
    </function>

    <function name="$fcerr" section="access" output="matrix">
      <description>
	<para>
	  Tem que ser acedido a seguir a um comando de predição
	  <cmdref targ="fcast"/>; retorna os  erros padrão de uma
	  predição, se disponível, numa matriz. Se o modelo em que
	  a predição se baseou é um sistema de equações a matriz 
	  retornada terá uma coluna por equação, caso contrário 
	  será um vector coluna.
	</para>
      </description>
    </function>

    <function name="$fevd" section="access" output="matrix">
      <description>
	<para>
	  Tem que ser acedido após a estimação de VAR. Retorna a 
	  matriz contendo a decomposição de erro da predição. Esta
	  matriz tem <math>h</math> linhas onde <math>h</math> é um
	  horizonte de predição, que pode ser escolhido com
	  <lit>set horizon</lit> ou, caso contrário, é determinado
	  automaticamente baseado na frequência dos dados.  No caso
	  de VAR com <math>p</math> variáveis, a matriz tem
	  <math>p</math><sup>2</sup> colunas. A fracção da predição
	  de erro para a variável <math>i</math> associável à inovação
          na variável <math>j</math> encontra-se na coluna
	  (<math>i</math> &minus; 1)<math>p</math> + <math>j</math>.
	</para>
      </description>
    </function>

    <function name="$Fstat" section="access" output="scalar">
      <description>
	<para>
	  Retorna a estatística F global do último modelo estimado,
	  se disponível.
	</para>
      </description>
    </function>

    <function name="$gmmcrit" section="access" output="scalar">
      <description>
	<para>
	  Tem que ser acedido a seguir a um bloco <lit>gmm</lit>. 
	  Retorna o valor da função objetivo no seu mínimo.
	</para>
      </description>
    </function>

    <function name="$h" section="access" output="series">
      <description>
	<para>
	  Tem que ser acedido a seguir a um comando <lit>garch</lit>. 
	  Retorna a série da variância condicional estimada.
	</para>
      </description>
    </function>

    <function name="$hausman" section="access" output="rvec">
      <description>
	<para>
	  Tem que ser acedido após a estimação de modelo <lit>tsls</lit> ou
	  <lit>painel</lit> com a opção de efeitos aleatórios. Retorna um vector <by
	    r="1" c="3"/> contendo o valor da estatística de teste Hausmam, 
	  com os graus de liberdade correspondentes e o valor p do teste, por
	  essa ordem.
	</para>
      </description>
    </function>

    <function name="$hqc" section="access" output="scalar">
      <description>
	<para>
	  Retorna o Critério de Informação de Hannan-Quinn para o último modelo
	  estimado, se disponível. Consultar <guideref
	  targ="select-criteria"/> para  detalhes sobre o cálculo.
	</para>
      </description>
    </function>

    <function name="$jalpha" section="access" output="matrix">
      <description>
	<para>
	  Tem que ser acedido após a estimação de VECM, e retorna a matriz das
	  cargas. Contém tantas linhas como as variáveis em VECM e o mesmo 
	  número de colunas que o nível de cointegração.
	</para>
      </description>
    </function>

    <function name="$jbeta" section="access" output="matrix">
      <description>
	<para>
	  Tem que ser acedido após a estimação de VECM, e retorna a matriz de
	  cointegração. Contém tantas linhas como as variáveis em VECM (mais 
	  um número de variáveis exógenas que estão restritas a um espaço de
	  cointegração, caso existam), e o mesmo número de colunas que o nível
	  de cointegração.
	</para>
      </description>
    </function>
